// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atbvkawlboidtbfczzzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0YnZrYXdsYm9pZHRiZmN6enp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDM5OTQsImV4cCI6MjA2MDM3OTk5NH0.E4f7B1qGYNudwa0aHFuzVjehsPwAQjovTcwlpkirKjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);